import type { Item } from '../types/item';

/**
 * Edge-case dataset: for each of the four media types, a *minimal* item
 * (required fields only) and a *maximal* item (every field populated), in both
 * Backlog and History membership. 4 types × 4 variants = 16 items. Used to
 * exercise the views against the corners of the schema.
 *
 * Required fields (present on every item, incl. minimal):
 *   id, type, title, status, is_purchased, is_prioritized,
 *   completed_dates, completed_years, tags, metadata.
 */
export const edgeSeed: Item[] = [
  // ----- BOOK -----------------------------------------------------------------
  {
    id: 'edge-book-minimal-backlog',
    type: 'book',
    title: 'Minimal Backlog Book',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: [],
    metadata: {},
  },
  {
    id: 'edge-book-maximal-backlog',
    type: 'book',
    title: 'Maximal Backlog Book',
    creator: 'Ada Author',
    cover: 'https://example.com/book-cover.jpg',
    thumbnail: 'https://example.com/book-thumb.jpg',
    release_date: '2023-05-01',
    description: 'Every optional field populated, never completed.',
    length: 432,
    length_unit: 'pages',
    community_rating: 8.4,
    my_rating: 8,
    provider: 'goodreads',
    recommended_by: 'Chuck',
    status: 'backlog',
    is_purchased: true,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    notes: 'Private note on the backlog book.',
    tags: ['sci-fi', 'owned'],
    metadata: {
      series: 'The Maximal Saga',
      series_number: 1,
      isbn: '9781234567897',
    },
  },
  {
    id: 'edge-book-minimal-history',
    type: 'book',
    title: 'Minimal History Book',
    status: 'inactive',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-03-12'],
    completed_years: [2025],
    tags: [],
    metadata: {},
  },
  {
    id: 'edge-book-maximal-history',
    type: 'book',
    title: 'Maximal History Book',
    creator: ['Ada Author', 'Bob Coauthor'],
    cover: 'https://example.com/book-cover2.jpg',
    thumbnail: 'https://example.com/book-thumb2.jpg',
    release_date: '2018-09-20',
    description: 'Every optional field populated, completed in two years.',
    length: 640,
    length_unit: 'pages',
    community_rating: 9.2,
    my_rating: 10,
    provider: 'goodreads',
    recommended_by: 'Dana',
    status: 'inactive',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2024-01-02', '2026-02-14'],
    completed_years: [2024, 2026],
    notes: 'Re-read once; even better the second time.',
    tags: ['fantasy', 'favorite'],
    metadata: {
      series: 'The Maximal Saga',
      series_number: 2,
      isbn: '9789876543210',
    },
  },

  // ----- MOVIE ----------------------------------------------------------------
  {
    id: 'edge-movie-minimal-backlog',
    type: 'movie',
    title: 'Minimal Backlog Movie',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: [],
    metadata: {},
  },
  {
    id: 'edge-movie-maximal-backlog',
    type: 'movie',
    title: 'Maximal Backlog Movie',
    creator: 'Dee Director',
    cover: 'https://example.com/movie-cover.jpg',
    thumbnail: 'https://example.com/movie-thumb.jpg',
    release_date: '2024-11-15',
    description: 'Every optional field populated, never watched.',
    length: 137,
    length_unit: 'min',
    community_rating: 7.8,
    my_rating: 7,
    provider: 'tmdb',
    recommended_by: 'Eli',
    status: 'in_progress',
    is_purchased: true,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    notes: 'Started watching, not finished.',
    tags: ['thriller'],
    metadata: {},
  },
  {
    id: 'edge-movie-minimal-history',
    type: 'movie',
    title: 'Minimal History Movie',
    status: 'inactive',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-07-04'],
    completed_years: [2025],
    tags: [],
    metadata: {},
  },
  {
    id: 'edge-movie-maximal-history',
    type: 'movie',
    title: 'Maximal History Movie',
    creator: 'Dee Director',
    cover: 'https://example.com/movie-cover2.jpg',
    thumbnail: 'https://example.com/movie-thumb2.jpg',
    release_date: '2010-07-16',
    description: 'Every optional field populated, watched twice.',
    length: 148,
    length_unit: 'min',
    community_rating: 8.4,
    my_rating: 9,
    provider: 'tmdb',
    recommended_by: 'Faye',
    status: 'inactive',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2024-12-31', '2026-01-01'],
    completed_years: [2024, 2026],
    notes: 'New Year double feature both years.',
    tags: ['sci-fi', 'rewatch'],
    metadata: {},
  },

  // ----- SHOW (per-season) ----------------------------------------------------
  {
    id: 'edge-show-minimal-backlog',
    type: 'show',
    title: 'Minimal Backlog Show',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: [],
    metadata: {
      show_tmdb_id: 100001,
      season_number: 1,
      episode_count: 8,
      episode_runtime: 50,
    },
  },
  {
    id: 'edge-show-maximal-backlog',
    type: 'show',
    title: 'Maximal Backlog Show',
    creator: ['Gus Creator', 'Hana Creator'],
    cover: 'https://example.com/show-cover.jpg',
    thumbnail: 'https://example.com/show-thumb.jpg',
    release_date: '2022-02-18',
    description: 'Every optional field populated, season not yet watched.',
    length: 480,
    length_unit: 'min',
    community_rating: 8.9,
    my_rating: 9,
    provider: 'tmdb',
    recommended_by: 'Iris',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    notes: 'Heard season 2 is even better.',
    tags: ['mystery', 'prestige'],
    metadata: {
      show_tmdb_id: 100002,
      season_number: 2,
      episode_count: 10,
      episode_runtime: 48,
    },
  },
  {
    id: 'edge-show-minimal-history',
    type: 'show',
    title: 'Minimal History Show',
    status: 'inactive',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-10-31'],
    completed_years: [2025],
    tags: [],
    metadata: {
      show_tmdb_id: 100003,
      season_number: 1,
      episode_count: 6,
      episode_runtime: 55,
    },
  },
  {
    id: 'edge-show-maximal-history',
    type: 'show',
    title: 'Maximal History Show',
    creator: 'Gus Creator',
    cover: 'https://example.com/show-cover2.jpg',
    thumbnail: 'https://example.com/show-thumb2.jpg',
    release_date: '2019-04-14',
    description:
      'Every optional field populated, season finished across two years.',
    length: 600,
    length_unit: 'min',
    community_rating: 9.3,
    my_rating: 10,
    provider: 'tmdb',
    recommended_by: 'Jude',
    status: 'inactive',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2024-06-09', '2026-03-03'],
    completed_years: [2024, 2026],
    notes: 'Binged, then rewatched the finale season.',
    tags: ['drama', 'rewatch'],
    metadata: {
      show_tmdb_id: 100004,
      season_number: 3,
      episode_count: 9,
      episode_runtime: 62,
    },
  },

  // ----- GAME -----------------------------------------------------------------
  {
    id: 'edge-game-minimal-backlog',
    type: 'game',
    title: 'Minimal Backlog Game',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: [],
    metadata: {},
  },
  {
    id: 'edge-game-maximal-backlog',
    type: 'game',
    title: 'Maximal Backlog Game',
    creator: 'Kilo Studios',
    cover: 'https://example.com/game-cover.jpg',
    thumbnail: 'https://example.com/game-thumb.jpg',
    release_date: '2025-09-30',
    description: 'Every optional field populated, in the wishlist.',
    length: 60,
    length_unit: 'hours',
    community_rating: 9.1,
    my_rating: 8,
    provider: 'igdb',
    recommended_by: 'Lena',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    notes: 'Waiting for a sale.',
    tags: ['rpg', 'wishlist'],
    metadata: { platform: 'PC' },
  },
  {
    id: 'edge-game-minimal-history',
    type: 'game',
    title: 'Minimal History Game',
    status: 'inactive',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-12-25'],
    completed_years: [2025],
    tags: [],
    metadata: {},
  },
  {
    id: 'edge-game-maximal-history',
    type: 'game',
    title: 'Maximal History Game',
    creator: 'Kilo Studios',
    cover: 'https://example.com/game-cover2.jpg',
    thumbnail: 'https://example.com/game-thumb2.jpg',
    release_date: '2017-03-03',
    description: 'Every optional field populated, finished in two years.',
    length: 90,
    length_unit: 'hours',
    community_rating: 9.7,
    my_rating: 10,
    provider: 'igdb',
    recommended_by: 'Milo',
    status: 'inactive',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2024-08-20', '2026-04-18'],
    completed_years: [2024, 2026],
    notes: 'Did a 100% run, then a replay on hard.',
    tags: ['adventure', 'replay'],
    metadata: { platform: 'Nintendo Switch' },
  },
];
