import type { Item } from '../types/item';

/**
 * Realistic dataset for eyeballing the views: for each media type, ~5 backlog
 * items, ~5 completed in 2026, and ~5 completed in 2025 (60 items total). Real
 * titles, creators, and release dates; ratings/lengths are plausible.
 *
 * `community_rating` is on the normalized 0–10 scale (Goodreads source values
 * are doubled). `completed_years` is recomputed at load time (see useSeed).
 *
 * Cover/thumbnail use a placeholder image service: real provider cover URLs are
 * opaque API-supplied paths, so genuine art only arrives once the add-flow/sync
 * milestone populates real items. The placeholders exercise the image code
 * paths in the meantime.
 */
const img = (label: string): Pick<Item, 'cover' | 'thumbnail'> => ({
  thumbnail: `https://placehold.co/185x278?text=${encodeURIComponent(label)}`,
  cover: `https://placehold.co/500x750?text=${encodeURIComponent(label)}`,
});

export const sampleSeed: Item[] = [
  // ===== BOOKS ================================================================
  // --- backlog ---
  {
    id: 'book-goodreads-20518872',
    type: 'book',
    title: 'The Three-Body Problem',
    creator: 'Liu Cixin',
    ...img('The Three-Body Problem'),
    release_date: '2008-01-01',
    description:
      'Against the backdrop of China’s Cultural Revolution, a secret military project makes first contact with an alien civilization.',
    length: 416,
    length_unit: 'pages',
    community_rating: 8.16,
    provider: 'goodreads',
    status: 'backlog',
    is_purchased: true,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    tags: ['sci-fi'],
    metadata: { series: "Remembrance of Earth's Past", series_number: 1 },
  },
  {
    id: 'book-goodreads-54493401',
    type: 'book',
    title: 'Project Hail Mary',
    creator: 'Andy Weir',
    ...img('Project Hail Mary'),
    release_date: '2021-05-04',
    description:
      'A lone astronaut wakes with no memory aboard a ship that is humanity’s last hope against an extinction-level threat.',
    length: 496,
    length_unit: 'pages',
    community_rating: 9.02,
    provider: 'goodreads',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    notes: 'Everyone keeps telling me to read this one.',
    tags: ['sci-fi'],
    metadata: {},
  },
  {
    id: 'book-goodreads-57945316',
    type: 'book',
    title: 'Babel',
    creator: 'R.F. Kuang',
    ...img('Babel'),
    release_date: '2022-08-23',
    description:
      'At an Oxford translation institute, magic is powered by language — and by the empire it serves.',
    length: 560,
    length_unit: 'pages',
    community_rating: 8.26,
    provider: 'goodreads',
    recommended_by: 'Priya',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['fantasy', 'historical'],
    metadata: {},
  },
  {
    id: 'book-goodreads-44767458',
    type: 'book',
    title: 'Dune',
    creator: 'Frank Herbert',
    ...img('Dune'),
    release_date: '1965-08-01',
    description:
      'On the desert planet Arrakis, a noble heir becomes the focal point of a struggle over the universe’s most valuable resource.',
    length: 412,
    length_unit: 'pages',
    community_rating: 8.54,
    provider: 'goodreads',
    status: 'backlog',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['sci-fi'],
    metadata: { series: 'Dune', series_number: 1 },
  },
  {
    id: 'book-goodreads-186074',
    type: 'book',
    title: 'The Name of the Wind',
    creator: 'Patrick Rothfuss',
    ...img('The Name of the Wind'),
    release_date: '2007-03-27',
    description:
      'A gifted young man recounts his rise from orphan to legendary, and notorious, arcanist.',
    length: 662,
    length_unit: 'pages',
    community_rating: 9.04,
    provider: 'goodreads',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['fantasy'],
    metadata: { series: 'The Kingkiller Chronicle', series_number: 1 },
  },
  // --- completed 2026 ---
  {
    id: 'book-goodreads-40046059',
    type: 'book',
    title: 'A Memory Called Empire',
    creator: 'Arkady Martine',
    ...img('A Memory Called Empire'),
    release_date: '2019-03-26',
    description:
      'An ambassador from a small mining station navigates intrigue at the heart of a vast, seductive empire.',
    length: 462,
    length_unit: 'pages',
    community_rating: 8.32,
    my_rating: 9,
    provider: 'goodreads',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2026-01-18'],
    completed_years: [2026],
    tags: ['sci-fi'],
    metadata: { series: 'Teixcalaan', series_number: 1 },
  },
  {
    id: 'book-goodreads-50202953',
    type: 'book',
    title: 'Piranesi',
    creator: 'Susanna Clarke',
    ...img('Piranesi'),
    release_date: '2020-09-15',
    description:
      'A man lives in an infinite house of statues and tides, slowly uncovering the truth of his world.',
    length: 245,
    length_unit: 'pages',
    community_rating: 8.48,
    my_rating: 10,
    provider: 'goodreads',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2026-02-09'],
    completed_years: [2026],
    notes: 'Quietly became one of my favorite books.',
    tags: ['fantasy'],
    metadata: {},
  },
  {
    id: 'book-goodreads-19161852',
    type: 'book',
    title: 'The Fifth Season',
    creator: 'N.K. Jemisin',
    ...img('The Fifth Season'),
    release_date: '2015-08-04',
    description:
      'On a world wracked by apocalyptic seasons, a mother searches for her daughter amid civilization’s collapse.',
    length: 468,
    length_unit: 'pages',
    community_rating: 8.68,
    my_rating: 9,
    provider: 'goodreads',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-03-22'],
    completed_years: [2026],
    tags: ['fantasy'],
    metadata: { series: 'The Broken Earth', series_number: 1 },
  },
  {
    id: 'book-goodreads-54120408',
    type: 'book',
    title: 'Klara and the Sun',
    creator: 'Kazuo Ishiguro',
    ...img('Klara and the Sun'),
    release_date: '2021-03-02',
    description:
      'An artificial friend observes the world with hope and devotion as she waits to be chosen.',
    length: 303,
    length_unit: 'pages',
    community_rating: 7.84,
    my_rating: 8,
    provider: 'goodreads',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2026-04-30'],
    completed_years: [2026],
    tags: ['sci-fi', 'literary'],
    metadata: {},
  },
  {
    id: 'book-goodreads-58784475',
    type: 'book',
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    creator: 'Gabrielle Zevin',
    ...img('Tomorrow and Tomorrow'),
    release_date: '2022-07-05',
    description:
      'Two friends build a life and a creative partnership through the video games they make together.',
    length: 401,
    length_unit: 'pages',
    community_rating: 8.34,
    my_rating: 9,
    provider: 'goodreads',
    recommended_by: 'Sam',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-05-11'],
    completed_years: [2026],
    tags: ['literary'],
    metadata: {},
  },
  // --- completed 2025 ---
  {
    id: 'book-goodreads-18423',
    type: 'book',
    title: 'The Left Hand of Darkness',
    creator: 'Ursula K. Le Guin',
    ...img('The Left Hand of Darkness'),
    release_date: '1969-03-01',
    description:
      'An envoy to a world without fixed gender learns the cost and meaning of trust across difference.',
    length: 304,
    length_unit: 'pages',
    community_rating: 8.16,
    my_rating: 10,
    provider: 'goodreads',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-02-14'],
    completed_years: [2025],
    notes: 'The ice-crossing chapters stuck with me for weeks.',
    tags: ['sci-fi'],
    metadata: { series: 'Hainish Cycle', series_number: 4 },
  },
  {
    id: 'book-goodreads-35959740',
    type: 'book',
    title: 'Circe',
    creator: 'Madeline Miller',
    ...img('Circe'),
    release_date: '2018-04-10',
    description:
      'The witch of Greek myth tells her own story of exile, power, and mortality.',
    length: 393,
    length_unit: 'pages',
    community_rating: 8.56,
    my_rating: 9,
    provider: 'goodreads',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-04-06'],
    completed_years: [2025],
    tags: ['fantasy', 'mythology'],
    metadata: {},
  },
  {
    id: 'book-goodreads-42046112',
    type: 'book',
    title: 'Recursion',
    creator: 'Blake Crouch',
    ...img('Recursion'),
    release_date: '2019-06-11',
    description:
      'A detective and a neuroscientist chase a technology that lets people relive — and rewrite — their memories.',
    length: 329,
    length_unit: 'pages',
    community_rating: 8.24,
    my_rating: 8,
    provider: 'goodreads',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-06-21'],
    completed_years: [2025],
    tags: ['sci-fi', 'thriller'],
    metadata: {},
  },
  {
    id: 'book-goodreads-41160292',
    type: 'book',
    title: 'Exhalation',
    creator: 'Ted Chiang',
    ...img('Exhalation'),
    release_date: '2019-05-07',
    description:
      'Nine speculative stories that turn rigorous ideas into deeply humane fiction.',
    length: 350,
    length_unit: 'pages',
    community_rating: 8.56,
    my_rating: 10,
    provider: 'goodreads',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-09-02'],
    completed_years: [2025],
    tags: ['sci-fi', 'short-stories'],
    metadata: {},
  },
  {
    id: 'book-goodreads-40275288',
    type: 'book',
    title: 'The Priory of the Orange Tree',
    creator: 'Samantha Shannon',
    ...img('The Priory of the Orange Tree'),
    release_date: '2019-02-26',
    description:
      'A standalone epic of queens, dragons, and divided faiths racing to stop an ancient evil.',
    length: 827,
    length_unit: 'pages',
    community_rating: 8.12,
    my_rating: 7,
    provider: 'goodreads',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-11-30'],
    completed_years: [2025],
    notes: 'Gorgeous, but it ran a bit long for me.',
    tags: ['fantasy'],
    metadata: { series: 'The Roots of Chaos', series_number: 1 },
  },

  // ===== MOVIES ===============================================================
  // --- backlog ---
  {
    id: 'movie-tmdb-872585',
    type: 'movie',
    title: 'Oppenheimer',
    creator: 'Christopher Nolan',
    ...img('Oppenheimer'),
    release_date: '2023-07-21',
    description:
      'The story of J. Robert Oppenheimer and the race to build the atomic bomb.',
    length: 180,
    length_unit: 'min',
    community_rating: 8.1,
    provider: 'tmdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    tags: ['drama', 'historical'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-792307',
    type: 'movie',
    title: 'Poor Things',
    creator: 'Yorgos Lanthimos',
    ...img('Poor Things'),
    release_date: '2023-12-08',
    description:
      'A woman brought back to life by an unorthodox scientist sets off on a wild journey of self-discovery.',
    length: 141,
    length_unit: 'min',
    community_rating: 7.8,
    provider: 'tmdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['comedy', 'sci-fi'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-693134',
    type: 'movie',
    title: 'Dune: Part Two',
    creator: 'Denis Villeneuve',
    ...img('Dune Part Two'),
    release_date: '2024-03-01',
    description:
      'Paul Atreides unites with the Fremen to wage war against those who destroyed his family.',
    length: 166,
    length_unit: 'min',
    community_rating: 8.2,
    provider: 'tmdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    notes: 'Want to rewatch Part One first.',
    tags: ['sci-fi'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-467244',
    type: 'movie',
    title: 'The Zone of Interest',
    creator: 'Jonathan Glazer',
    ...img('The Zone of Interest'),
    release_date: '2023-12-15',
    description:
      'A commandant of Auschwitz and his wife strive to build an idyllic life beside the camp wall.',
    length: 105,
    length_unit: 'min',
    community_rating: 7.4,
    provider: 'tmdb',
    recommended_by: 'Tariq',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['drama', 'historical'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-466420',
    type: 'movie',
    title: 'Killers of the Flower Moon',
    creator: 'Martin Scorsese',
    ...img('Killers of the Flower Moon'),
    release_date: '2023-10-20',
    description:
      'Members of the Osage Nation are murdered under mysterious circumstances in 1920s Oklahoma.',
    length: 206,
    length_unit: 'min',
    community_rating: 7.5,
    provider: 'tmdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['drama', 'crime'],
    metadata: {},
  },
  // --- completed 2026 ---
  {
    id: 'movie-tmdb-666277',
    type: 'movie',
    title: 'Past Lives',
    creator: 'Celine Song',
    ...img('Past Lives'),
    release_date: '2023-06-02',
    description:
      'Two childhood friends reunite decades later to confront the lives they did and didn’t choose.',
    length: 105,
    length_unit: 'min',
    community_rating: 7.8,
    my_rating: 9,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-01-05'],
    completed_years: [2026],
    tags: ['romance', 'drama'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-915935',
    type: 'movie',
    title: 'Anatomy of a Fall',
    creator: 'Justine Triet',
    ...img('Anatomy of a Fall'),
    release_date: '2023-08-23',
    description:
      'A writer stands trial for her husband’s death as the truth of their marriage is dissected.',
    length: 151,
    length_unit: 'min',
    community_rating: 7.6,
    my_rating: 9,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-02-20'],
    completed_years: [2026],
    tags: ['drama', 'thriller'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-840430',
    type: 'movie',
    title: 'The Holdovers',
    creator: 'Alexander Payne',
    ...img('The Holdovers'),
    release_date: '2023-10-27',
    description:
      'A curmudgeonly teacher is stuck over the holidays with a troubled student and the school’s grieving cook.',
    length: 133,
    length_unit: 'min',
    community_rating: 7.9,
    my_rating: 8,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-03-14'],
    completed_years: [2026],
    tags: ['comedy', 'drama'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-545611',
    type: 'movie',
    title: 'Everything Everywhere All at Once',
    creator: 'Daniel Kwan, Daniel Scheinert',
    ...img('Everything Everywhere All at Once'),
    release_date: '2022-03-24',
    description:
      'A laundromat owner is swept into a multiverse adventure to save reality and her family.',
    length: 139,
    length_unit: 'min',
    community_rating: 7.8,
    my_rating: 10,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2026-04-02'],
    completed_years: [2026],
    notes: 'Funnier and sadder than I expected.',
    tags: ['sci-fi', 'comedy'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-815904',
    type: 'movie',
    title: 'Aftersun',
    creator: 'Charlotte Wells',
    ...img('Aftersun'),
    release_date: '2022-10-21',
    description:
      'A woman recalls a seaside holiday with her young father, piecing together what she couldn’t see then.',
    length: 102,
    length_unit: 'min',
    community_rating: 7.7,
    my_rating: 9,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-05-19'],
    completed_years: [2026],
    tags: ['drama'],
    metadata: {},
  },
  // --- completed 2025 ---
  {
    id: 'movie-tmdb-496243',
    type: 'movie',
    title: 'Parasite',
    creator: 'Bong Joon-ho',
    ...img('Parasite'),
    release_date: '2019-05-30',
    description:
      'A poor family schemes their way into the household of a wealthy one, with explosive consequences.',
    length: 132,
    length_unit: 'min',
    community_rating: 8.5,
    my_rating: 10,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-01-12'],
    completed_years: [2025],
    tags: ['thriller', 'drama'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-244786',
    type: 'movie',
    title: 'Whiplash',
    creator: 'Damien Chazelle',
    ...img('Whiplash'),
    release_date: '2014-10-10',
    description:
      'A young drummer clashes with a ruthless instructor who will stop at nothing to push genius.',
    length: 106,
    length_unit: 'min',
    community_rating: 8.4,
    my_rating: 10,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-03-08'],
    completed_years: [2025],
    tags: ['drama', 'music'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-329865',
    type: 'movie',
    title: 'Arrival',
    creator: 'Denis Villeneuve',
    ...img('Arrival'),
    release_date: '2016-11-11',
    description:
      'A linguist races to communicate with newly arrived aliens before fear ignites a global war.',
    length: 116,
    length_unit: 'min',
    community_rating: 7.6,
    my_rating: 9,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-05-25'],
    completed_years: [2025],
    tags: ['sci-fi'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-313369',
    type: 'movie',
    title: 'La La Land',
    creator: 'Damien Chazelle',
    ...img('La La Land'),
    release_date: '2016-12-09',
    description:
      'A jazz musician and an aspiring actress fall in love while chasing their dreams in Los Angeles.',
    length: 128,
    length_unit: 'min',
    community_rating: 7.9,
    my_rating: 8,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-08-17'],
    completed_years: [2025],
    tags: ['romance', 'music'],
    metadata: {},
  },
  {
    id: 'movie-tmdb-76341',
    type: 'movie',
    title: 'Mad Max: Fury Road',
    creator: 'George Miller',
    ...img('Mad Max Fury Road'),
    release_date: '2015-05-15',
    description:
      'In a post-apocalyptic wasteland, a drifter and a rebel commander flee a tyrant across the desert.',
    length: 120,
    length_unit: 'min',
    community_rating: 7.6,
    my_rating: 9,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-10-04'],
    completed_years: [2025],
    tags: ['action', 'sci-fi'],
    metadata: {},
  },

  // ===== SHOWS (per-season) ===================================================
  // --- backlog ---
  {
    id: 'show-tmdb-127532-s1',
    type: 'show',
    title: 'Shōgun',
    creator: 'Justin Marks, Rachel Kondo',
    ...img('Shogun S1'),
    release_date: '2024-02-27',
    description:
      'In feudal Japan, a stranded English pilot is caught between a powerful lord and a translator with her own secrets.',
    length: 600,
    length_unit: 'min',
    community_rating: 8.5,
    provider: 'tmdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    tags: ['drama', 'historical'],
    metadata: {
      show_tmdb_id: 127532,
      season_number: 1,
      episode_count: 10,
      episode_runtime: 60,
    },
  },
  {
    id: 'show-tmdb-136315-s1',
    type: 'show',
    title: 'Silo',
    creator: 'Graham Yost',
    ...img('Silo S1'),
    release_date: '2023-05-05',
    description:
      'Thousands live in a giant underground silo, forbidden to ask why — until someone does.',
    length: 500,
    length_unit: 'min',
    community_rating: 8.0,
    provider: 'tmdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['sci-fi', 'mystery'],
    metadata: {
      show_tmdb_id: 136315,
      season_number: 1,
      episode_count: 10,
      episode_runtime: 50,
    },
  },
  {
    id: 'show-tmdb-105248-s1',
    type: 'show',
    title: 'Andor',
    creator: 'Tony Gilroy',
    ...img('Andor S1'),
    release_date: '2022-09-21',
    description:
      'The early days of the rebellion against the Empire, told through one reluctant recruit.',
    length: 540,
    length_unit: 'min',
    community_rating: 8.4,
    provider: 'tmdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    notes: 'Heard this is the best Star Wars in years.',
    tags: ['sci-fi'],
    metadata: {
      show_tmdb_id: 105248,
      season_number: 1,
      episode_count: 12,
      episode_runtime: 45,
    },
  },
  {
    id: 'show-tmdb-153312-s1',
    type: 'show',
    title: 'Fallout',
    creator: 'Geneva Robertson-Dworet, Graham Wagner',
    ...img('Fallout S1'),
    release_date: '2024-04-10',
    description:
      'Two centuries after the bombs, a vault dweller ventures into the irradiated ruins of Los Angeles.',
    length: 480,
    length_unit: 'min',
    community_rating: 8.3,
    provider: 'tmdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['sci-fi', 'action'],
    metadata: {
      show_tmdb_id: 153312,
      season_number: 1,
      episode_count: 8,
      episode_runtime: 60,
    },
  },
  {
    id: 'show-tmdb-136902-s3',
    type: 'show',
    title: 'The Bear',
    creator: 'Christopher Storer',
    ...img('The Bear S3'),
    release_date: '2024-06-27',
    description:
      'A fine-dining chef fights to turn his late brother’s sandwich shop into something great.',
    length: 300,
    length_unit: 'min',
    community_rating: 8.4,
    provider: 'tmdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['comedy', 'drama'],
    metadata: {
      show_tmdb_id: 136902,
      season_number: 3,
      episode_count: 10,
      episode_runtime: 30,
    },
  },
  // --- completed 2026 ---
  {
    id: 'show-tmdb-95396-s2',
    type: 'show',
    title: 'Severance',
    creator: 'Dan Erickson',
    ...img('Severance S2'),
    release_date: '2025-01-17',
    description:
      'The severed workers of Lumon push deeper into the conspiracy splitting their work and home selves.',
    length: 500,
    length_unit: 'min',
    community_rating: 8.7,
    my_rating: 10,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-02-01'],
    completed_years: [2026],
    notes: 'The wait was worth it.',
    tags: ['sci-fi', 'mystery'],
    metadata: {
      show_tmdb_id: 95396,
      season_number: 2,
      episode_count: 10,
      episode_runtime: 50,
    },
  },
  {
    id: 'show-tmdb-128067-s4',
    type: 'show',
    title: 'Slow Horses',
    creator: 'Will Smith',
    ...img('Slow Horses S4'),
    release_date: '2024-09-04',
    description:
      'The washed-up spies of Slough House stumble into a conspiracy after a bombing in London.',
    length: 270,
    length_unit: 'min',
    community_rating: 8.1,
    my_rating: 9,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-03-09'],
    completed_years: [2026],
    tags: ['thriller', 'spy'],
    metadata: {
      show_tmdb_id: 128067,
      season_number: 4,
      episode_count: 6,
      episode_runtime: 45,
    },
  },
  {
    id: 'show-tmdb-114461-s1',
    type: 'show',
    title: 'The Penguin',
    creator: 'Lauren LeFranc',
    ...img('The Penguin S1'),
    release_date: '2024-09-19',
    description:
      'Oswald Cobb claws his way up Gotham’s criminal underworld in the wake of the Riddler’s flood.',
    length: 440,
    length_unit: 'min',
    community_rating: 8.5,
    my_rating: 9,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-04-11'],
    completed_years: [2026],
    tags: ['crime', 'drama'],
    metadata: {
      show_tmdb_id: 114461,
      season_number: 1,
      episode_count: 8,
      episode_runtime: 55,
    },
  },
  {
    id: 'show-tmdb-138502-s1',
    type: 'show',
    title: 'Ripley',
    creator: 'Steven Zaillian',
    ...img('Ripley S1'),
    release_date: '2024-04-04',
    description:
      'A grifter sent to Italy to retrieve a wealthy heir slips into a life of deceit and murder.',
    length: 440,
    length_unit: 'min',
    community_rating: 8.0,
    my_rating: 8,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-05-06'],
    completed_years: [2026],
    tags: ['thriller', 'drama'],
    metadata: {
      show_tmdb_id: 138502,
      season_number: 1,
      episode_count: 8,
      episode_runtime: 55,
    },
  },
  {
    id: 'show-tmdb-115394-s2',
    type: 'show',
    title: 'Shrinking',
    creator: 'Bill Lawrence, Jason Segel, Brett Goldstein',
    ...img('Shrinking S2'),
    release_date: '2024-10-16',
    description:
      'A grieving therapist keeps breaking the rules by telling his clients exactly what he thinks.',
    length: 384,
    length_unit: 'min',
    community_rating: 8.2,
    my_rating: 8,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2026-06-01'],
    completed_years: [2026],
    tags: ['comedy', 'drama'],
    metadata: {
      show_tmdb_id: 115394,
      season_number: 2,
      episode_count: 12,
      episode_runtime: 32,
    },
  },
  // --- completed 2025 ---
  {
    id: 'show-tmdb-95396-s1',
    type: 'show',
    title: 'Severance',
    creator: 'Dan Erickson',
    ...img('Severance S1'),
    release_date: '2022-02-18',
    description:
      'Employees at Lumon surgically divide their memories between work and personal life — until cracks appear.',
    length: 450,
    length_unit: 'min',
    community_rating: 8.7,
    my_rating: 10,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-01-20'],
    completed_years: [2025],
    tags: ['sci-fi', 'mystery'],
    metadata: {
      show_tmdb_id: 95396,
      season_number: 1,
      episode_count: 9,
      episode_runtime: 50,
    },
  },
  {
    id: 'show-tmdb-100088-s1',
    type: 'show',
    title: 'The Last of Us',
    creator: 'Craig Mazin, Neil Druckmann',
    ...img('The Last of Us S1'),
    release_date: '2023-01-15',
    description:
      'A hardened survivor smuggles a teenage girl across a fungal-apocalypse America.',
    length: 495,
    length_unit: 'min',
    community_rating: 8.6,
    my_rating: 9,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-03-15'],
    completed_years: [2025],
    tags: ['drama', 'post-apocalyptic'],
    metadata: {
      show_tmdb_id: 100088,
      season_number: 1,
      episode_count: 9,
      episode_runtime: 55,
    },
  },
  {
    id: 'show-tmdb-1535-s4',
    type: 'show',
    title: 'Succession',
    creator: 'Jesse Armstrong',
    ...img('Succession S4'),
    release_date: '2023-03-26',
    description:
      'The Roy siblings wage a final, brutal contest for control of their father’s media empire.',
    length: 600,
    length_unit: 'min',
    community_rating: 8.8,
    my_rating: 10,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-06-12'],
    completed_years: [2025],
    notes: 'Best final season of anything in ages.',
    tags: ['drama'],
    metadata: {
      show_tmdb_id: 1535,
      season_number: 4,
      episode_count: 10,
      episode_runtime: 60,
    },
  },
  {
    id: 'show-tmdb-97546-s3',
    type: 'show',
    title: 'Ted Lasso',
    creator: 'Bill Lawrence, Jason Sudeikis, Brendan Hunt, Joe Kelly',
    ...img('Ted Lasso S3'),
    release_date: '2023-03-15',
    description:
      'An optimistic American coach guides his English football club through its biggest season yet.',
    length: 540,
    length_unit: 'min',
    community_rating: 8.3,
    my_rating: 7,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-09-08'],
    completed_years: [2025],
    tags: ['comedy', 'sports'],
    metadata: {
      show_tmdb_id: 97546,
      season_number: 3,
      episode_count: 12,
      episode_runtime: 45,
    },
  },
  {
    id: 'show-tmdb-208857-s1',
    type: 'show',
    title: 'Beef',
    creator: 'Lee Sung Jin',
    ...img('Beef S1'),
    release_date: '2023-04-06',
    description:
      'A road-rage incident spirals into an all-consuming feud between two strangers.',
    length: 350,
    length_unit: 'min',
    community_rating: 8.0,
    my_rating: 9,
    provider: 'tmdb',
    status: 'complete',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: ['2025-11-22'],
    completed_years: [2025],
    tags: ['comedy', 'drama'],
    metadata: {
      show_tmdb_id: 208857,
      season_number: 1,
      episode_count: 10,
      episode_runtime: 35,
    },
  },

  // ===== GAMES ================================================================
  // --- backlog ---
  {
    id: 'game-igdb-119133',
    type: 'game',
    title: 'Elden Ring',
    creator: 'FromSoftware',
    ...img('Elden Ring'),
    release_date: '2022-02-25',
    description:
      'An open-world action RPG across the Lands Between, shaped with George R. R. Martin.',
    length: 70,
    length_unit: 'hours',
    community_rating: 9.5,
    provider: 'igdb',
    status: 'backlog',
    is_purchased: true,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    notes: 'Bought it on release and still haven’t started.',
    tags: ['rpg', 'soulslike'],
    metadata: { platform: 'PC' },
  },
  {
    id: 'game-igdb-119171',
    type: 'game',
    title: "Baldur's Gate 3",
    creator: 'Larian Studios',
    ...img("Baldur's Gate 3"),
    release_date: '2023-08-03',
    description:
      'A sprawling D&D-based RPG where nearly every choice reshapes the story.',
    length: 90,
    length_unit: 'hours',
    community_rating: 9.6,
    provider: 'igdb',
    status: 'backlog',
    is_purchased: true,
    is_prioritized: true,
    completed_dates: [],
    completed_years: [],
    tags: ['rpg'],
    metadata: { platform: 'PC' },
  },
  {
    id: 'game-igdb-217590',
    type: 'game',
    title: 'Metaphor: ReFantazio',
    creator: 'Atlus',
    ...img('Metaphor ReFantazio'),
    release_date: '2024-10-11',
    description:
      'A fantasy JRPG from the Persona team about an election to become king.',
    length: 80,
    length_unit: 'hours',
    community_rating: 9.2,
    provider: 'igdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['rpg', 'jrpg'],
    metadata: { platform: 'PC' },
  },
  {
    id: 'game-igdb-119388',
    type: 'game',
    title: 'The Legend of Zelda: Tears of the Kingdom',
    creator: 'Nintendo',
    ...img('Tears of the Kingdom'),
    release_date: '2023-05-12',
    description:
      'Link explores the skies and depths of Hyrule with a new set of world-bending abilities.',
    length: 60,
    length_unit: 'hours',
    community_rating: 9.4,
    provider: 'igdb',
    status: 'backlog',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['adventure'],
    metadata: { platform: 'Nintendo Switch' },
  },
  {
    id: 'game-igdb-217274',
    type: 'game',
    title: 'Hades II',
    creator: 'Supergiant Games',
    ...img('Hades II'),
    release_date: '2024-05-06',
    description:
      'A roguelike sequel following the Princess of the Underworld against the Titan of Time.',
    length: 40,
    length_unit: 'hours',
    community_rating: 9.0,
    provider: 'igdb',
    status: 'backlog',
    is_purchased: false,
    is_prioritized: false,
    completed_dates: [],
    completed_years: [],
    tags: ['roguelike', 'action'],
    metadata: { platform: 'PC' },
  },
  // --- completed 2026 ---
  {
    id: 'game-igdb-284764',
    type: 'game',
    title: 'Astro Bot',
    creator: 'Team Asobi',
    ...img('Astro Bot'),
    release_date: '2024-09-06',
    description:
      'A joyful 3D platformer celebrating PlayStation history across inventive worlds.',
    length: 15,
    length_unit: 'hours',
    community_rating: 9.4,
    my_rating: 10,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2026-01-25'],
    completed_years: [2026],
    notes: 'Pure delight start to finish.',
    tags: ['platformer'],
    metadata: { platform: 'PlayStation 5' },
  },
  {
    id: 'game-igdb-227555',
    type: 'game',
    title: 'Final Fantasy VII Rebirth',
    creator: 'Square Enix',
    ...img('Final Fantasy VII Rebirth'),
    release_date: '2024-02-29',
    description:
      'The second chapter of the FF7 remake trilogy opens up a vast world beyond Midgar.',
    length: 80,
    length_unit: 'hours',
    community_rating: 9.2,
    my_rating: 9,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2026-03-30'],
    completed_years: [2026],
    tags: ['rpg', 'jrpg'],
    metadata: { platform: 'PlayStation 5' },
  },
  {
    id: 'game-igdb-249106',
    type: 'game',
    title: 'Balatro',
    creator: 'LocalThunk',
    ...img('Balatro'),
    release_date: '2024-02-20',
    description:
      'A poker-themed roguelike deckbuilder that turns a humble hand into wild combos.',
    length: 30,
    length_unit: 'hours',
    community_rating: 9.1,
    my_rating: 9,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2026-04-15'],
    completed_years: [2026],
    notes: 'Lost an absurd number of evenings to this.',
    tags: ['roguelike', 'cards'],
    metadata: { platform: 'PC' },
  },
  {
    id: 'game-igdb-237895',
    type: 'game',
    title: 'Pacific Drive',
    creator: 'Ironwood Studios',
    ...img('Pacific Drive'),
    release_date: '2024-02-22',
    description:
      'A survival driving game where your station wagon is your lifeline through an anomalous zone.',
    length: 25,
    length_unit: 'hours',
    community_rating: 8.0,
    my_rating: 8,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2026-05-02'],
    completed_years: [2026],
    tags: ['survival'],
    metadata: { platform: 'PC' },
  },
  {
    id: 'game-igdb-265433',
    type: 'game',
    title: 'Animal Well',
    creator: 'Billy Basso',
    ...img('Animal Well'),
    release_date: '2024-05-09',
    description:
      'A dense, secretive metroidvania set in a glowing labyrinth of creatures and puzzles.',
    length: 12,
    length_unit: 'hours',
    community_rating: 8.8,
    my_rating: 9,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2026-06-10'],
    completed_years: [2026],
    tags: ['metroidvania'],
    metadata: { platform: 'PC' },
  },
  // --- completed 2025 ---
  {
    id: 'game-igdb-134585',
    type: 'game',
    title: 'God of War Ragnarök',
    creator: 'Santa Monica Studio',
    ...img('God of War Ragnarök'),
    release_date: '2022-11-09',
    description:
      'Kratos and Atreus face the coming of Ragnarök across the Nine Realms.',
    length: 40,
    length_unit: 'hours',
    community_rating: 9.3,
    my_rating: 9,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-02-02'],
    completed_years: [2025],
    tags: ['action', 'adventure'],
    metadata: { platform: 'PlayStation 5' },
  },
  {
    id: 'game-igdb-115279',
    type: 'game',
    title: 'Hi-Fi Rush',
    creator: 'Tango Gameworks',
    ...img('Hi-Fi Rush'),
    release_date: '2023-01-25',
    description:
      'A rhythm-action brawler where the whole world pulses to the beat of the soundtrack.',
    length: 12,
    length_unit: 'hours',
    community_rating: 8.9,
    my_rating: 9,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-04-19'],
    completed_years: [2025],
    tags: ['action', 'rhythm'],
    metadata: { platform: 'PC' },
  },
  {
    id: 'game-igdb-143103',
    type: 'game',
    title: 'Pizza Tower',
    creator: 'Tour De Pizza',
    ...img('Pizza Tower'),
    release_date: '2023-01-26',
    description:
      'A frantic, hand-drawn platformer about a chef racing to save his pizzeria.',
    length: 10,
    length_unit: 'hours',
    community_rating: 8.7,
    my_rating: 8,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-06-30'],
    completed_years: [2025],
    tags: ['platformer'],
    metadata: { platform: 'PC' },
  },
  {
    id: 'game-igdb-126459',
    type: 'game',
    title: 'Resident Evil 4',
    creator: 'Capcom',
    ...img('Resident Evil 4'),
    release_date: '2023-03-24',
    description:
      'A remake of the survival-horror classic as agent Leon Kennedy rescues the president’s daughter.',
    length: 18,
    length_unit: 'hours',
    community_rating: 9.1,
    my_rating: 9,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-09-13'],
    completed_years: [2025],
    tags: ['horror', 'action'],
    metadata: { platform: 'PC' },
  },
  {
    id: 'game-igdb-217587',
    type: 'game',
    title: 'Cocoon',
    creator: 'Geometric Interactive',
    ...img('Cocoon'),
    release_date: '2023-09-29',
    description:
      'A serene puzzle-adventure of nesting worlds carried inside orbs on your back.',
    length: 6,
    length_unit: 'hours',
    community_rating: 8.6,
    my_rating: 8,
    provider: 'igdb',
    status: 'complete',
    is_purchased: true,
    is_prioritized: false,
    completed_dates: ['2025-12-07'],
    completed_years: [2025],
    tags: ['puzzle'],
    metadata: { platform: 'PC' },
  },
];
